name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      # This placeholder allows build without a real project ID; replace in repo secrets if needed
      NEXT_PUBLIC_PROJECT_ID: REPLACE_WITH_REOWN_PROJECT_ID
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.2.20'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

